language: java
jdk: oraclejdk8
install: true
before_script:
  - export MAJOR_VERSION=`sed -n 's/^ext\.majorVersion = \(.*\)$/\1/p' build.gradle`
  - export MINOR_VERSION=`sed -n 's/^ext\.minorVersion = \(.*\)$/\1/p' build.gradle`
  - export MC_VERSION=`sed -n 's/^ext\.minecraftVersion = "\(.*\)"$/\1/p' build.gradle`
  - export VERSION_STRING=$MAJOR_VERSION.$MINOR_VERSION.$TRAVIS_BUILD_NUMBER-mc$MC_VERSION
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - 'sed -i "s/^\(version: \).*\$/\1$VERSION_STRING/g" src/main/resources/plugin.yml'
script: ./gradlew build
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
  - if [ "$TRAVIS_BRANCH" != "$MC_VERSION" ]; then exit 0; fi
  - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then exit 0; fi
  - ./gradlew shadowJar
  - cp build/libs/RedisProvider-all.jar ./RedisProvider-v$VERSION_STRING.jar
  - export GIT_TAG=v$VERSION_STRING
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true
  api_key: $GITHUB_OAUTH_TOKEN
  file: ./RedisProvider-v$VERSION_STRING.jar
  on:
    tags: false
    all_branches: true